(()=>{
const ID='__acl64',KEY='__acl64cache'; if(document.getElementById(ID)){document.getElementById(ID).remove();return}
let S={labs:{},echo:{},inbody:{},reports:[],mode:'AUTO'}; try{S={...S,...JSON.parse(sessionStorage.getItem(KEY)||'{}')}}catch(e){}
const save=()=>sessionStorage.setItem(KEY,JSON.stringify(S));
const txt=()=>document.body?.innerText||''; const clean=s=>String(s||'').replace(/\s+/g,' ').trim();
const flag=(v,n,lo,hi)=>{let x=parseFloat(v); if(!Number.isFinite(x))return v; return (Number.isFinite(hi)&&x>hi?'H ':(Number.isFinite(lo)&&x<lo?'L ':''))+v};
function rows(){return [...document.querySelectorAll('tr')].map(tr=>[...tr.querySelectorAll('th,td')].map(td=>clean(td.innerText))).filter(r=>r.length>=5)}
const aliases={hba1c:/^(HbA1c|HbA1c\(紫頭管\))$/i,eag:/Estimated average glucose|eAG/i,gluAC:/Glucose-AC|飯前血糖/i,gluPC:/Glucose-PC|飯後血糖/i,tc:/^(Cholesterol|TC)$/i,tg:/^(TG|Triglyceride)/i,hdl:/HDL/i,ldl:/LDL/i,ua:/Uric Acid/i,bun:/^BUN$/i,cr:/^Creatinine$/i,egfr:/^eGFR$/i,ast:/^(S-GOT|AST)$/i,alt:/^(S-GPT|ALT)$/i,tsh:/^TSH$/i,ft4:/^(Free T4|FT4)$/i,t3:/^T3$/i,wbc:/^(WBC|白血球)/i,hb:/^(HGB|Hemoglobin|Hb)$/i,mcv:/^MCV$/i,plt:/^(Platelet|Plt)/i,uacr:/Microalbumin\/Cr urine ratio|Microalbumin\/Cr/i,upcr:/UPCR/i,pra:/Renin activity|PRA/i,pac:/Aldosterone/i};
function parseLabs(){for(const r of rows()){let joined=r.join(' | '); let name=''; for(const c of r){if(Object.values(aliases).some(re=>re.test(c))){name=c;break}} if(!name)continue; let key=Object.keys(aliases).find(k=>aliases[k].test(name)); if(!key)continue;
 // Require row-local numeric result; ignore test codes/dates/reference columns by locating name then nearest plausible numeric cells after it.
 let ni=r.indexOf(name), cand=[]; for(let i=ni+1;i<r.length;i++){let c=r[i]; if(/^[-+]?\d+(?:\.\d+)?$/.test(c))cand.push({i,v:c})} if(!cand.length)continue; let val=cand[0].v;
 // Typical HIS columns: name then result then normal/lower/upper. derive limits only from cells after result.
 let after=r.slice(cand[0].i+1).filter(c=>/^[-+]?\d+(?:\.\d+)?$/.test(c)).map(Number), lo=NaN,hi=NaN; if(after.length>=2){lo=after[0];hi=after[1]}
 S.labs[key]={v:flag(val,key,lo,hi),raw:val};
 }
 // UACR HIS ratio often reports 0.01 Ratio = 10 mg/g
 if(S.labs.uacr){let x=parseFloat(S.labs.uacr.raw); if(x<1)S.labs.uacr.v=(S.labs.uacr.v.startsWith('H ')?'H ':'')+(x*1000).toFixed(x*1000%1?1:0)}
 save()}
function parseEcho(t){if(!/echo|M-MODE|DOPPLAER|DOPPLER|LVEF|diastolic function/i.test(t))return; let m;
 if(m=t.match(/LVEF\s*(?:about)?\s*(\d+(?:\.\d+)?)\s*%/i))S.echo.lvef=m[1];
 if(/left ventricular hypertrophy|\bLVH\b/i.test(t))S.echo.lvh=true;
 if(/preserved LV systolic|normal LV systolic function/i.test(t))S.echo.sys='preserved LV systolic function';
 if(/normal diastolic function|Suggestive normal diastolic function/i.test(t))S.echo.dia='normal LV diastolic function';
 for(const sev of ['trivial','mild','moderate','severe']){let re=new RegExp(sev+'\\s+([^\\n.]{0,45}(?:MR|TR|PR)[^\\n.]*)','ig'); while(m=re.exec(t)){for(const v of ['MR','PR','TR'])if(new RegExp('\\b'+v+'\\b','i').test(m[1]))S.echo[v]=sev}}
 if(m=t.match(/estimated PASP\s*(?:about)?\s*(\d+(?:\.\d+)?)\s*mmHg/i))S.echo.pasp=m[1]; save()}
function parseInbody(t){if(!/身體組成分析|InBody|PBF|體脂肪率/i.test(t))return; const pats={BW:/(?:體重|BW)\s*[:：]?\s*(\d+(?:\.\d+)?)/i,BMI:/\bBMI\s*[:：]?\s*(\d+(?:\.\d+)?)/i,PBF:/(?:PBF|體脂肪率)\s*(?:\(%\))?\s*[:：]?\s*(\d+(?:\.\d+)?)/i,BFM:/(?:BFM|體脂肪量)\s*[:：]?\s*(\d+(?:\.\d+)?)/i,SMM:/(?:SMM|肌肉量)\s*[:：]?\s*(\d+(?:\.\d+)?)/i,VFA:/(?:VFA|內臟脂肪指數)\s*[:：]?\s*(\d+(?:\.\d+)?)/i}; for(const[k,re]of Object.entries(pats)){let m=t.match(re);if(m)S.inbody[k]=m[1]} save()}
function report(t){parseEcho(t);parseInbody(t)}
function fmt(){parseLabs();report(txt());let L=S.labs, lines=[],a=[]; if(L.hba1c){let x=`HbA1c ${L.hba1c.v}%`;if(L.eag)x+=` (eAG ${L.eag.v} mg/dL)`;a.push(x)} if(L.gluAC)a.push(`Glu-AC ${L.gluAC.v} mg/dL`);else if(L.gluPC)a.push(`Glu-PC ${L.gluPC.v} mg/dL`); if(L.uacr)a.push(`UACR ${L.uacr.v} mg/g`);if(L.upcr)a.push(`UPCR ${L.upcr.v} mg/g`);if(a.length)lines.push('• '+a.join('; '));
 a=[];let lip=['tc','tg','hdl','ldl'].filter(k=>L[k]);if(lip.length)a.push(`${lip.map(k=>({tc:'TC',tg:'TG',hdl:'HDL',ldl:'LDL'}[k])).join('/')} ${lip.map(k=>L[k].v).join('/')} mg/dL`);if(L.ua)a.push(`UA ${L.ua.v} mg/dL`);if(a.length)lines.push('• '+a.join('; '));
 a=[];if(L.bun)a.push(`BUN ${L.bun.v}`);if(L.cr)a.push(`Cr ${L.cr.v}`);if(L.egfr)a.push(`eGFR ${L.egfr.v}`);if(a.length)lines.push('• '+a.join('/')); if(L.ast||L.alt)lines[lines.length-1]+=`; ${L.ast?'AST '+L.ast.v:''}${L.ast&&L.alt?'/':''}${L.alt?'ALT '+L.alt.v:''} U/L`;
 a=[];if(L.ft4)a.push(`FT4 ${L.ft4.v} ng/dL`);if(L.tsh)a.push(`TSH ${L.tsh.v} μIU/mL`);if(L.t3)a.push(`T3 ${L.t3.v} ng/mL`);if(a.length)lines.push('• '+a.join('; '));
 if(L.pra||L.pac){a=[];if(L.pra)a.push(`PRA ${L.pra.v} ng/mL/hr`);if(L.pac)a.push(`PAC ${L.pac.v} ng/dL`);lines.push('• '+a.join('; '))}
 let E=S.echo;if(Object.keys(E).length){a=[];if(E.lvh)a.push('LVH');if(E.lvef)a.push(`LVEF ${E.lvef}%`);if(E.sys)a.push(E.sys);if(E.dia)a.push(E.dia);for(const sev of ['trivial','mild','moderate','severe']){let vs=['MR','PR','TR'].filter(v=>E[v]===sev);if(vs.length)a.push(`${sev} ${vs.join('/')}`)}if(E.pasp)a.push(`PASP ${E.pasp} mmHg`);if(a.length)lines.push('• Echo: '+a.join('; '))}
 let I=S.inbody;if(Object.keys(I).length){let p=[];for(const k of ['BW','BMI','PBF','BFM','SMM','VFA'])if(I[k])p.push(`${k} ${I[k]}${k==='PBF'?'%':''}`);if(p.length)lines.push('• InBody: '+p.join('; '))}
 return lines.join('\n')}
const d=document.createElement('div');d.id=ID;d.style='position:fixed;z-index:2147483647;right:12px;top:12px;width:min(690px,calc(100vw - 24px));max-height:calc(100vh - 24px);overflow:auto;background:#fff;color:#243746;border:1px solid #ccd3db;border-radius:14px;box-shadow:0 12px 40px #0004;padding:14px;font:14px Arial,sans-serif';d.innerHTML=`<div style="display:flex;justify-content:space-between"><b>Auto Clinical Lab v6.4</b><button id=aX>×</button></div><div style="margin:8px 0;font-size:12px">Mode <select id=aM><option>AUTO</option><option>OPD</option><option>IPD</option></select> <span id=aD></span></div><pre id=aR style="white-space:pre-wrap;background:#f7f9fb;padding:10px;border-radius:9px;min-height:50px"></pre><div style="display:flex;gap:8px;flex-wrap:wrap"><button id=aC>Copy</button><button id=aK>Clear cache</button><button id=aS>Capture screen</button></div><div style="font-size:11px;color:#667085;margin-top:8px">Echo accumulates while scrolling. ECG screenshot capture is available; automatic ECG image OCR is not enabled in this browser-only build.</div>`;document.body.appendChild(d);
const R=d.querySelector('#aR'),D=d.querySelector('#aD'); function draw(){let t=txt();let det=/\b住院\b/.test(t)?'IPD':/\b門診\b|\b急診\b/.test(t)?'OPD':'?';D.textContent='Detected: '+det;R.textContent=fmt()}
let tm;const sch=()=>{clearTimeout(tm);tm=setTimeout(draw,300)};addEventListener('scroll',sch,{passive:true});new MutationObserver(sch).observe(document.body,{subtree:true,childList:true,characterData:true});
d.querySelector('#aC').onclick=()=>navigator.clipboard.writeText(R.textContent);d.querySelector('#aK').onclick=()=>{S={labs:{},echo:{},inbody:{},reports:[],mode:'AUTO'};sessionStorage.removeItem(KEY);R.textContent='';};d.querySelector('#aX').onclick=()=>d.remove();d.querySelector('#aS').onclick=async()=>{try{let st=await navigator.mediaDevices.getDisplayMedia({video:true});let v=document.createElement('video');v.srcObject=st;await v.play();let c=document.createElement('canvas');c.width=v.videoWidth;c.height=v.videoHeight;c.getContext('2d').drawImage(v,0,0);st.getTracks().forEach(x=>x.stop());let w=open();w.document.write('<title>Captured screen</title><img style="max-width:100%" src="'+c.toDataURL('image/png')+'">')}catch(e){}};draw();
})()