(()=>{
const ID='__emrAutoClinicalV5',STORE='__emrAutoClinicalCacheV5';
const old=document.getElementById(ID);if(old){old.remove();return;}
const norm=s=>(s||'').replace(/\u00a0/g,' ').replace(/[ \t]+/g,' ').trim();
const num=s=>{const m=norm(s).match(/[-+]?\d+(?:\.\d+)?/);return m?m[0]:null};
const rocDate=s=>{const m=norm(s).match(/\b(\d{2,3})[\/.-](\d{1,2})[\/.-](\d{1,2})\b/);return m?`${m[1]}/${String(m[2]).padStart(2,'0')}/${String(m[3]).padStart(2,'0')}`:''};
const shortDate=s=>{const d=rocDate(s);return d?d.split('/').slice(1).join('/'):''};
const timeOf=s=>{const m=norm(s).match(/\b([01]?\d|2[0-3]):([0-5]\d)\b/);return m?`${m[1].padStart(2,'0')}:${m[2]}`:''};
const ageOf=s=>{for(const p of [/(?:年齡|年龄)\s*[:：]?\s*(\d{1,3})\s*(?:歲|岁)?/i,/\bAge\s*[:：]?\s*(\d{1,3})\b/i,/\((\d{1,3})\s*歲\)/]){const m=s.match(p);if(m&&+m[1]>0&&+m[1]<130)return +m[1]}return null};
let state;try{state=JSON.parse(sessionStorage.getItem(STORE)||'null')}catch(e){};if(!state)state={records:{},cultures:{},age:null,modeOverride:'AUTO'};
const save=()=>sessionStorage.setItem(STORE,JSON.stringify(state));
function exactCells(text){return [...document.querySelectorAll('td,th')].filter(x=>norm(x.innerText)===text)}
function detectMode(){if(state.modeOverride&&state.modeOverride!=='AUTO')return state.modeOverride;const counts={Inpatient:0,ER:0,OPD:0};for(const el of document.querySelectorAll('td,th')){const t=norm(el.innerText);if(t==='住院')counts.Inpatient++;else if(t==='急診')counts.ER++;else if(/^(門診|門診診療|門診檢驗)$/.test(t))counts.OPD++;}return Object.entries(counts).sort((a,b)=>b[1]-a[1])[0][1]?Object.entries(counts).sort((a,b)=>b[1]-a[1])[0][0]:'OPD'}
const unitMap={hba1c:'%',eag:'mg/dL',gluac:'mg/dL',glupc:'mg/dL',glucose:'mg/dL',uacr:'mg/g',upcr:'mg/g',tc:'mg/dL',tg:'mg/dL',hdl:'mg/dL',ldl:'mg/dL',ua:'mg/dL',bun:'mg/dL',cr:'mg/dL',egfr:'',na:'mmol/L',k:'mmol/L',cl:'mmol/L',ca:'mg/dL',p:'mg/dL',mg:'mg/dL',ast:'U/L',alt:'U/L',tbil:'mg/dL',dbil:'mg/dL',alb:'g/dL',crp:'mg/dL',pct:'ng/mL',lactate:'mg/dL',amylase:'U/L',lipase:'U/L',tsh:'uIU/mL',ft4:'ng/dL',t3:'ng/mL',wbc:'×10^3/uL',hb:'g/dL',plt:'×10^3/uL',neut:'%',lymp:'%',mono:'%',eosi:'%',baso:'%',pt:'sec',inr:'',aptt:'sec',tnt:'ng/L',bloodket:'',stoolob:'',stooltf:'',urineSG:'',urinePH:'',urinePro:'',urineGlu:'',urineKet:'',urineNit:'',urineLE:'',urineRBC:'/HPF',urineWBC:'/HPF',bacteria:'',ph:'',pco2:'mmHg',po2:'mmHg',hco3:'mmol/L',be:'mmol/L',so2:'%'};
function classify(name,section=''){
 const n=norm(name).toLowerCase(),s=norm(section).toLowerCase();
 if(/estimated average glucose|\beag\b/.test(n))return'eag'; if(/hba1c/.test(n))return'hba1c';
 if(/one.?touch|病房專用.*glucose/.test(n))return'glucose'; if(/glucose[- ]?pc|飯後血糖/.test(n))return'glupc'; if(/glucose[- ]?ac|空腹.*glucose/.test(n))return'gluac';
 if(/uacr|albumin.*creatinine.*1000/.test(n))return'uacr'; if(/\bupcr\b|protein.*creatinine.*ratio/.test(n))return'upcr';
 if(/l\.?d\.?l.*cholesterol|\bldl(?:-c)?\b/.test(n))return'ldl'; if(/h\.?d\.?l.*cholesterol|\bhdl(?:-c)?\b/.test(n))return'hdl'; if(/triglyceride|\btg\b/.test(n))return'tg'; if((/cholesterol|\btc\b/.test(n))&&!/ldl|hdl/.test(n))return'tc'; if(/uric acid/.test(n))return'ua';
 if(/\bbun\b|blood urea nitrogen/.test(n))return'bun'; if(/\begfr\b/.test(n))return'egfr'; if(/creatinine/.test(n)&&!/urine|尿|spot/.test(n))return'cr';
 if(/^(na|鈉)$/.test(n))return'na'; if(/^(k|鉀)$/.test(n))return'k'; if(/^(cl|氯)$/.test(n))return'cl'; if(/^ca(?: \(b\))?$/.test(n)||/^ca 鈣$/.test(n))return'ca'; if(/^p$|磷/.test(n))return'p'; if(/^mg$|mg 鎂|鎂/.test(n))return'mg';
 if(/s-got|\bast\b/.test(n))return'ast'; if(/s-gpt|\balt\b/.test(n))return'alt'; if(/bilirubin total/.test(n))return'tbil'; if(/bilirubin direct/.test(n))return'dbil'; if(/^albumin$/.test(n))return'alb';
 if(/^crp$/.test(n))return'crp'; if(/procalcitonin|\bpct\b/.test(n))return'pct'; if(/lactic acid|lactate/.test(n))return'lactate'; if(/amylase/.test(n))return'amylase'; if(/lipase/.test(n))return'lipase';
 if(/^tsh$/.test(n))return'tsh'; if(/free\s*t4|\bft4\b/.test(n))return'ft4'; if(/^t3$/.test(n))return't3';
 if(/白血球計數|^w\.?b\.?c$|\bwbc\b/.test(n))return'wbc'; if(/hemoglobin|血色素|\bhgb\b/.test(n))return'hb'; if(/platelet|血小板/.test(n))return'plt'; if(/neut/.test(n))return'neut'; if(/lymp/.test(n))return'lymp'; if(/mono/.test(n))return'mono'; if(/eosi/.test(n))return'eosi'; if(/baso/.test(n))return'baso';
 if(/^prothrombin time$|^pt$/.test(n))return'pt'; if(/^inr$/.test(n))return'inr'; if(/aptt/.test(n))return'aptt'; if(/troponin.*t/.test(n))return'tnt'; if(/ketone body.*blood/.test(n))return'bloodket';
 if(/stool occult blood|fobt/.test(n))return'stoolob'; if(/transferrin-stool/.test(n))return'stooltf';
 if(/尿比重|sp\.gr/.test(n))return'urineSG'; if(/酸鹼度ph/.test(n))return'urinePH'; if(/尿蛋白pro/.test(n))return'urinePro'; if(/尿糖glu/.test(n))return'urineGlu'; if(/酮體ket/.test(n))return'urineKet'; if(/亞硝酸鹽nit/.test(n))return'urineNit'; if(/leukocyte esterase/.test(n))return'urineLE'; if(/尿紅血球|r\.b\.c\./.test(n))return'urineRBC'; if(/尿白血球|w\.b\.c\./.test(n))return'urineWBC'; if(/細菌bacteria/.test(n))return'bacteria';
 if(/blood gas/.test(s)||/氣體分析|venous blood gas/.test(s)){if(/^ph$/.test(n))return'ph';if(/pco2/.test(n))return'pco2';if(/^po2$/.test(n))return'po2';if(/^chco3$/.test(n))return'hco3';if(/^be$/.test(n))return'be';if(/so2\(c\)/.test(n))return'so2';}
 return null;
}
function cleanResult(v,key){v=norm(v);if(!v)return null;if(/negative/i.test(v))return'(-)';if(/positive/i.test(v))return'(+)';if(key==='bloodket'||/^urine/.test(key)||key==='bacteria'||key.startsWith('stool'))return v.replace(/Negative/ig,'(-)');return num(v)||v}
function headerMap(table){const rows=[...table.rows];for(const r of rows.slice(0,6)){const c=[...r.cells].map(x=>norm(x.innerText));const m={};c.forEach((x,i)=>{if(/細項名稱|檢驗名稱/.test(x))m.name=i;if(/檢驗值/.test(x))m.value=i;if(/完報日期|最終完報日時/.test(x))m.date=i;if(/^單位$/.test(x))m.unit=i;});if(m.name!==undefined&&m.value!==undefined)return m;}return null}
function sectionText(table){let t=norm(table.innerText);const prev=table.previousElementSibling;if(prev)t+=' '+norm(prev.innerText);return t.slice(0,1200)}
function extractTables(){let added=0;state.age=state.age||ageOf(document.body.innerText);for(const table of document.querySelectorAll('table')){const map=headerMap(table);if(!map)continue;const sec=sectionText(table);const gasType=/venous blood gas/i.test(sec)?'VBG':(/blood gas|氣體分析/i.test(sec)?'ABG':'');for(const r of table.rows){const c=[...r.cells].map(x=>norm(x.innerText));if(c.length<=Math.max(map.name,map.value))continue;const name=c[map.name]||'';const key=classify(name,sec);if(!key)continue;let value=cleanResult(c[map.value],key);if(value==null)continue;const rowText=norm(r.innerText);const date=shortDate(c[map.date]||rowText),time=timeOf(c[map.date]||rowText),unit=(c[map.unit]||unitMap[key]||'').replace('10^3/ul','×10^3/uL');const sig=[key,date,time,value,gasType].join('|');if(!state.records[sig]){state.records[sig]={key,value,date,time,unit,name,gasType};added++;}}}save();return added}
function records(){return Object.values(state.records).sort((a,b)=>((b.date||'')+' '+(b.time||'')).localeCompare((a.date||'')+' '+(a.time||'')))}
function latest(key){return records().find(x=>x.key===key)||null}
function byDate(date){return records().filter(x=>x.date===date)}
function first(arr,key){return arr.find(x=>x.key===key)}
function value(arr,key){const r=first(arr,key);return r&&r.value}
function packPairs(arr,pairs,unit=''){const got=pairs.filter(([k])=>value(arr,k)!=null);return got.length?`${got.map(x=>x[1]).join('/')} ${got.map(x=>value(arr,x[0])).join('/')}${unit?' '+unit:''}`:''}
function fib4(arr){const ast=+value(arr,'ast'),alt=+value(arr,'alt'),plt=+value(arr,'plt'),age=state.age;if(!age||!ast||!alt||!plt)return'';const f=age*ast/(plt*Math.sqrt(alt));if(!isFinite(f))return'';const risk=age>=65?(f<2?'low':f<=2.67?'intermediate':'high'):(f<1.3?'low':f<=2.67?'intermediate':'high');return`FIB-4 ${f.toFixed(2)} (${risk} risk${age<35?'; limited accuracy age <35':''})`}
function fmtOPD(){const a=records(),lines=[];let p=[];const h=first(a,'hba1c'),e=first(a,'eag');if(h)p.push(`HbA1c ${h.value}%${e?` (eAG ${e.value} mg/dL)`:''}`);for(const [k,l,u] of [['gluac','Glu-AC','mg/dL'],['uacr','UACR','mg/g'],['upcr','UPCR','mg/g']]){const r=first(a,k);if(r)p.push(`${l} ${r.value} ${u}`)}if(p.length)lines.push('• '+p.join('; '));p=[];const lip=packPairs(a,[['tc','TC'],['tg','TG'],['hdl','HDL'],['ldl','LDL']],'mg/dL');if(lip)p.push(lip);if(value(a,'ua'))p.push(`UA ${value(a,'ua')} mg/dL`);if(p.length)lines.push('• '+p.join('; '));p=[];const renal=packPairs(a,[['bun','BUN'],['cr','Cr'],['egfr','eGFR']]);if(renal)p.push(renal);const liver=packPairs(a,[['ast','AST'],['alt','ALT']],'U/L');if(liver)p.push(liver);if(p.length)lines.push('• '+p.join('; '));p=[];for(const [k,l,u] of [['tsh','TSH','uIU/mL'],['ft4','FT4','ng/dL'],['t3','T3','ng/mL']])if(value(a,k))p.push(`${l} ${value(a,k)} ${u}`);if(p.length)lines.push('• '+p.join('; '));p=[];const c=packPairs(a,[['wbc','WBC'],['hb','Hb'],['plt','Plt']]);if(c)p.push(c);const f=fib4(a);if(f)p.push(f);if(p.length)lines.push('• '+p.join('; '));return lines.join('\n')}
function fmtUA(a){const p=[];for(const [k,l] of [['urineSG','SG'],['urinePH','pH'],['urinePro','Protein'],['urineGlu','Glucose'],['urineKet','Ketone'],['urineRBC','RBC'],['urineWBC','WBC'],['bacteria','Bacteria'],['urineNit','Nitrite'],['urineLE','LE']]){if(value(a,k)!=null)p.push(`${l} ${value(a,k)}${k==='urineRBC'||k==='urineWBC'?'/HPF':''}`)}return p.length?'U/A: '+p.join('; '):''}
function fmtDate(date){const a=byDate(date),lines=[date];let p=[];const cbc=packPairs(a,[['wbc','WBC'],['hb','Hb'],['plt','Plt']]);if(cbc)p.push('CBC: '+cbc);const diff=packPairs(a,[['neut','N'],['lymp','L'],['mono','M'],['eosi','E'],['baso','B']],'%');if(diff)p.push(diff);if(p.length)lines.push('• '+p.join('; '));p=[];const renal=packPairs(a,[['bun','BUN'],['cr','Cr'],['egfr','eGFR']]);if(renal)p.push(renal);const el=packPairs(a,[['na','Na'],['k','K'],['cl','Cl']]);if(el)p.push(el);const camg=packPairs(a,[['ca','Ca'],['p','P'],['mg','Mg']]);if(camg)p.push(camg);if(p.length)lines.push('• '+p.join('; '));p=[];const liver=packPairs(a,[['ast','AST'],['alt','ALT'],['tbil','T-bil'],['dbil','D-bil'],['alb','Alb']]);if(liver)p.push(liver);for(const [k,l,u] of [['crp','CRP','mg/dL'],['pct','PCT','ng/mL'],['lactate','Lactate','mg/dL'],['tnt','hs-TnT','ng/L']])if(value(a,k))p.push(`${l} ${value(a,k)} ${u}`);if(p.length)lines.push('• '+p.join('; '));const h=first(a,'hba1c'),e=first(a,'eag');if(h)lines.push(`• HbA1c ${h.value}%${e?` (eAG ${e.value} mg/dL)`:''}`);const coag=packPairs(a,[['pt','PT'],['inr','INR'],['aptt','aPTT']]);if(coag)lines.push('• '+coag);const ua=fmtUA(a);if(ua)lines.push('• '+ua);if(value(a,'bloodket'))lines.push(`• Blood ketone ${value(a,'bloodket')}`);for(const gt of ['ABG','VBG']){const g=a.filter(x=>x.gasType===gt);if(g.length){const gp=packPairs(g,[['ph','pH'],['pco2','pCO2'],['hco3','HCO3'],['be','BE'],['po2','pO2'],['so2','sO2']]);if(gp)lines.push(`• ${gt}: ${gp}`)}}const glucose=a.filter(x=>x.key==='glucose').sort((x,y)=>(x.time||'').localeCompare(y.time||''));if(glucose.length)lines.push('• Glucose: '+glucose.map(x=>`${x.time||'--:--'} ${x.value}`).join(' → ')+' mg/dL');for(const [k,l] of [['stoolob','Stool OB'],['stooltf','Stool transferrin']])if(value(a,k))lines.push(`• ${l} ${value(a,k)}`);const cultures=Object.values(state.cultures).filter(x=>x.date===date&&x.result);for(const c of cultures)lines.push(`• ${c.label}: ${c.result}`);return lines.join('\n')}
function output(){const mode=detectMode();if(mode==='OPD')return fmtOPD()||'尚未辨識到可整理的檢驗數據。';const ds=[...new Set(records().map(x=>x.date).filter(Boolean))].sort().reverse();let out=ds.map(fmtDate).filter(Boolean).join('\n\n');const undated=Object.values(state.cultures).filter(x=>!x.date&&x.result);if(undated.length)out+=(out?'\n\n':'')+undated.map(c=>`• ${c.label}: ${c.result}`).join('\n');return out||'尚未辨識到可整理的檢驗數據。'}
// Culture: follow pointer/click context, then bind only visible final-result popup to that culture.
let activeCulture=null,lastX=0,lastY=0;
function cultureFromNode(node){const tr=node&&node.closest&&node.closest('tr');if(!tr)return null;const txt=norm(tr.innerText);if(!/culture|培養/i.test(txt))return null;const table=tr.closest('table');const sec=table?sectionText(table):txt;let specimen=/tip/i.test(txt+sec)?'Tip':/urine|尿/i.test(txt+sec)?'Urine':/blood|血液|血培/i.test(txt+sec)?'Blood':'';let label=/tip/i.test(txt)?'Tip culture':/urine/i.test(txt)?'Urine culture':/anaer|厭氧/i.test(txt)?'Blood culture (anaerobic)':'Blood culture';const date=shortDate(txt+sec),time=timeOf(txt);const key=[label,specimen,date,time,txt.slice(0,80)].join('|');return{key,label,specimen,date,time,rowText:txt}}
function setActive(node){const c=cultureFromNode(node);if(c){activeCulture=c;metaCulture.textContent=`Culture focus: ${c.label}${c.date?' '+c.date:''}`}}
function visible(el){const r=el.getBoundingClientRect(),cs=getComputedStyle(el);return r.width>0&&r.height>0&&cs.display!=='none'&&cs.visibility!=='hidden'&&+cs.opacity!==0}
function parseVisibleCultureResult(){if(!activeCulture)return;let best=null;for(const el of document.querySelectorAll('div,table,tbody,tr,td')){if(!visible(el))continue;const t=norm(el.innerText);if(!/結果值\s*[:：]/.test(t)||t.length>1200)continue;if(!best||t.length<best.length)best=t}if(!best)return;const rm=best.match(/結果值\s*[:：]\s*([^\n]+)/i),sm=best.match(/檢體\s*[:：]\s*([^\n]+)/i);if(!rm)return;const result=norm(rm[1]),spec=sm?norm(sm[1]):'';if(spec&&activeCulture.specimen&&!new RegExp(activeCulture.specimen,'i').test(spec))return;if(!result||/^\d{1,3}$/.test(result))return;state.cultures[activeCulture.key]={...activeCulture,result};save()}
document.addEventListener('mousemove',e=>{lastX=e.clientX;lastY=e.clientY;const els=document.elementsFromPoint(lastX,lastY);for(const el of els){const c=cultureFromNode(el);if(c){activeCulture=c;metaCulture.textContent=`Culture focus: ${c.label}${c.date?' '+c.date:''}`;break}}},{capture:true,passive:true});
document.addEventListener('click',e=>setActive(e.target),true);
const box=document.createElement('div');box.id=ID;Object.assign(box.style,{position:'fixed',right:'12px',top:'12px',zIndex:2147483647,width:'min(720px,calc(100vw - 24px))',maxHeight:'calc(100vh - 24px)',overflow:'auto',background:'#fff',color:'#243746',border:'1px solid #cfd4dc',borderRadius:'14px',boxShadow:'0 12px 40px rgba(0,0,0,.24)',padding:'14px',fontFamily:'Arial,"Microsoft JhengHei",sans-serif'});
box.innerHTML=`<div style="display:flex;justify-content:space-between;align-items:center;gap:8px"><strong>Auto Clinical Lab</strong><button id="x" style="border:0;background:#fff;font-size:20px">×</button></div><div style="display:flex;gap:8px;align-items:center;flex-wrap:wrap;margin:8px 0"><label>Mode</label><select id="mode"><option>AUTO</option><option>OPD</option><option>ER</option><option>Inpatient</option></select><span id="det" style="font-size:12px;color:#667085"></span></div><div id="culture" style="font-size:12px;color:#9a3412;margin:4px 0">Culture focus: none</div><pre id="res" style="white-space:pre-wrap;line-height:1.65;background:#f8fafc;padding:10px;border-radius:9px;font:14px/1.65 inherit"></pre><div style="display:flex;gap:8px;flex-wrap:wrap"><button id="copy" style="padding:8px 14px;border:0;border-radius:8px;background:#059669;color:#fff;font-weight:700">Copy</button><button id="clear" style="padding:8px 14px;border:1px solid #ccd5dd;border-radius:8px;background:#fff">Clear cache</button></div><div id="meta" style="font-size:12px;color:#667085;margin-top:7px"></div>`;document.body.appendChild(box);
const res=box.querySelector('#res'),meta=box.querySelector('#meta'),det=box.querySelector('#det'),metaCulture=box.querySelector('#culture'),modeSel=box.querySelector('#mode');modeSel.value=state.modeOverride||'AUTO';
modeSel.onchange=()=>{state.modeOverride=modeSel.value;save();refresh()};
let timer;function refresh(){extractTables();parseVisibleCultureResult();res.textContent=output();det.textContent=`Detected: ${detectMode()}`;meta.textContent=`Age: ${state.age??'未讀取'} ｜ Labs ${records().length} ｜ Cultures ${Object.keys(state.cultures).length} ｜ ${new Date().toLocaleTimeString()}`}
function schedule(){clearTimeout(timer);timer=setTimeout(refresh,180)}const mo=new MutationObserver(schedule);mo.observe(document.body,{subtree:true,childList:true,characterData:true});window.addEventListener('scroll',schedule,{passive:true});
box.querySelector('#copy').onclick=async()=>{try{await navigator.clipboard.writeText(res.textContent)}catch(e){const t=document.createElement('textarea');t.value=res.textContent;document.body.appendChild(t);t.select();document.execCommand('copy');t.remove()}};
box.querySelector('#clear').onclick=()=>{state={records:{},cultures:{},age:ageOf(document.body.innerText),modeOverride:modeSel.value};save();activeCulture=null;metaCulture.textContent='Culture focus: none';refresh()};box.querySelector('#x').onclick=()=>{mo.disconnect();box.remove()};refresh();
})();
