(()=>{
const VERSION='v6';
const ID='__emrAutoClinicalV6',STORE='__emrAutoClinicalCacheV6';
const old=document.getElementById(ID);if(old){old.remove();return;}
const norm=s=>(s||'').replace(/\u00a0/g,' ').replace(/[ \t]+/g,' ').trim();
const num=s=>{const m=norm(s).match(/[-+]?\d+(?:\.\d+)?/);return m?m[0]:null};
const rocDate=s=>{const m=norm(s).match(/\b(\d{2,3})[\/.-](\d{1,2})[\/.-](\d{1,2})\b/);return m?`${m[1]}/${String(m[2]).padStart(2,'0')}/${String(m[3]).padStart(2,'0')}`:''};
const shortDate=s=>{const d=rocDate(s);return d?d.split('/').slice(1).join('/'):''};
const timeOf=s=>{const m=norm(s).match(/\b([01]?\d|2[0-3]):([0-5]\d)\b/);return m?`${m[1].padStart(2,'0')}:${m[2]}`:''};
const ageOf=s=>{for(const p of [/(?:年齡|年龄)\s*[:：]?\s*(\d{1,3})\s*(?:歲|岁)?/i,/\bAge\s*[:：]?\s*(\d{1,3})\b/i,/\((\d{1,3})\s*歲\)/]){const m=s.match(p);if(m&&+m[1]>0&&+m[1]<130)return +m[1]}return null};
let state;try{state=JSON.parse(sessionStorage.getItem(STORE)||'null')}catch(e){}
if(!state)state={records:{},cultures:{},pathology:{},age:null,modeOverride:'AUTO',blockedFingerprint:null};
state.records=state.records||{};state.cultures=state.cultures||{};state.pathology=state.pathology||{};
const save=()=>sessionStorage.setItem(STORE,JSON.stringify(state));
function detectMode(){if(state.modeOverride&&state.modeOverride!=='AUTO')return state.modeOverride;const counts={Inpatient:0,ER:0,OPD:0};for(const el of document.querySelectorAll('td,th')){if(el.closest('#'+ID))continue;const t=norm(el.innerText);if(t==='住院')counts.Inpatient++;else if(t==='急診')counts.ER++;else if(/^(門診|門診診療|門診檢驗)$/.test(t))counts.OPD++;}const ranked=Object.entries(counts).sort((a,b)=>b[1]-a[1]);return ranked[0][1]?ranked[0][0]:'OPD'}
const unitMap={hba1c:'%',eag:'mg/dL',gluac:'mg/dL',glupc:'mg/dL',glupc2h:'mg/dL',glucose:'mg/dL',uacr:'mg/g',upcr:'mg/g',tc:'mg/dL',tg:'mg/dL',hdl:'mg/dL',ldl:'mg/dL',ua:'mg/dL',bun:'mg/dL',cr:'mg/dL',egfr:'',na:'mmol/L',k:'mmol/L',cl:'mmol/L',ca:'mg/dL',p:'mg/dL',mg:'mg/dL',ast:'U/L',alt:'U/L',tbil:'mg/dL',dbil:'mg/dL',alb:'g/dL',crp:'mg/dL',pct:'ng/mL',lactate:'mg/dL',amylase:'U/L',lipase:'U/L',tsh:'uIU/mL',ft4:'ng/dL',t3:'ng/mL',pac:'ng/dL',pra:'ng/mL/hr',arr:'ng/dL/(ng/mL/hr)',wbc:'×10^3/uL',hb:'g/dL',plt:'×10^3/uL',neut:'%',lymp:'%',mono:'%',eosi:'%',baso:'%',pt:'sec',inr:'',aptt:'sec',tnt:'ng/L',bloodket:'',stoolob:'',stooltf:'',urineSG:'',urinePH:'',urinePro:'',urineGlu:'',urineKet:'',urineNit:'',urineLE:'',urineRBC:'/HPF',urineWBC:'/HPF',bacteria:'',ph:'',pco2:'mmHg',po2:'mmHg',hco3:'mmol/L',be:'mmol/L',so2:'%'};
function classify(name,section=''){
 const n=norm(name).toLowerCase(),s=norm(section).toLowerCase();
 if(/estimated average glucose|\beag\b/.test(n))return'eag'; if(/hba1c/.test(n))return'hba1c';
 if(/75\s*(?:g|公克).*?(?:2\s*(?:h|hr|hour)|兩小時|二小時).*glucose|口服75公克葡萄糖兩小時後.*glucose|glucose.*(?:2\s*(?:h|hr)|兩小時).*75/i.test(name))return'glupc2h';
 if(/one.?touch|病房專用.*glucose/.test(n))return'glucose'; if(/glucose[- ]?pc|飯後血糖/.test(n))return'glupc'; if(/glucose[- ]?ac|空腹.*glucose/.test(n))return'gluac';
 if(/uacr|albumin.*creatinine.*1000/.test(n))return'uacr'; if(/\bupcr\b|protein.*creatinine.*ratio/.test(n))return'upcr';
 if(/aldosterone.*renin.*ratio|\barr\b|醛固酮.*腎素.*比/.test(n))return'arr';
 if(/aldosterone|醛固酮/.test(n))return'pac'; if(/plasma renin activity|\bpra\b|renin activity|腎素活性/.test(n))return'pra';
 if(/l\.?d\.?l.*cholesterol|\bldl(?:-c)?\b/.test(n))return'ldl'; if(/h\.?d\.?l.*cholesterol|\bhdl(?:-c)?\b/.test(n))return'hdl'; if(/triglyceride|\btg\b/.test(n))return'tg'; if((/cholesterol|\btc\b/.test(n))&&!/ldl|hdl/.test(n))return'tc'; if(/uric acid/.test(n))return'ua';
 if(/\bbun\b|blood urea nitrogen/.test(n))return'bun'; if(/\begfr\b/.test(n))return'egfr'; if(/creatinine/.test(n)&&!/urine|尿|spot/.test(n))return'cr';
 if(/^(na|鈉)$/.test(n))return'na'; if(/^(k|鉀)$/.test(n))return'k'; if(/^(cl|氯)$/.test(n))return'cl'; if(/^ca(?: \(b\))?$/.test(n)||/^ca 鈣$/.test(n))return'ca'; if(/^p$|磷/.test(n))return'p'; if(/^mg$|mg 鎂|鎂/.test(n))return'mg';
 if(/s-got|\bast\b/.test(n))return'ast'; if(/s-gpt|\balt\b/.test(n))return'alt'; if(/bilirubin total/.test(n))return'tbil'; if(/bilirubin direct/.test(n))return'dbil'; if(/^albumin$/.test(n))return'alb';
 if(/^crp$/.test(n))return'crp'; if(/procalcitonin|\bpct\b/.test(n))return'pct'; if(/lactic acid|lactate/.test(n))return'lactate'; if(/amylase/.test(n))return'amylase'; if(/lipase/.test(n))return'lipase';
 if(/^tsh$/.test(n))return'tsh'; if(/free\s*t4|\bft4\b/.test(n))return'ft4'; if(/^t3$/.test(n))return't3';
 if(/白血球計數|^w\.?b\.?c$|\bwbc\b/.test(n))return'wbc'; if(/hemoglobin|血色素|\bhgb\b/.test(n))return'hb'; if(/platelet|血小板/.test(n))return'plt'; if(/neut/.test(n))return'neut'; if(/lymp/.test(n))return'lymp'; if(/mono/.test(n))return'mono'; if(/eosi/.test(n))return'eosi'; if(/baso/.test(n))return'baso';
 if(/^prothrombin time$|^pt$/.test(n))return'pt'; if(/^inr$/.test(n))return'inr'; if(/aptt/.test(n))return'aptt'; if(/troponin.*t/.test(n))return'tnt'; if(/ketone body.*blood/.test(n))return'bloodket';
 if(/stool occult blood|fobt/.test(n))return'stoolob'; if(/transferrin-stool/.test(n))return'stooltf';
 if(/尿比重|sp\.gr/.test(n))return'urineSG'; if(/酸鹼度ph/.test(n))return'urinePH'; if(/尿蛋白pro/.test(n))return'urinePro'; if(/尿糖glu/.test(n))return'urineGlu'; if(/酮體ket/.test(n))return'urineKet'; if(/亞硝酸鹽nit/.test(n))return'urineNit'; if(/leukocyte esterase/.test(n))return'urineLE'; if(/尿紅血球|r\.b\.c\./.test(n))return'urineRBC'; if(/尿白血球|w\.b\.c\./.test(n))return'urineWBC'; if(/細菌bacteria/.test(n))return'bacteria';
 if(/blood gas/.test(s)||/氣體分析|venous blood gas/.test(s)){if(/^ph$/.test(n))return'ph';if(/pco2/.test(n))return'pco2';if(/^po2$/.test(n))return'po2';if(/^chco3$/.test(n))return'hco3';if(/^be$/.test(n))return'be';if(/so2\(c\)/.test(n))return'so2';}
 return null;
}
function cleanResult(v,key){v=norm(v);if(!v)return null;if(/negative/i.test(v))return'(-)';if(/positive/i.test(v))return'(+)';if(key==='bloodket'||/^urine/.test(key)||key==='bacteria'||key.startsWith('stool'))return v.replace(/Negative/ig,'(-)');return num(v)||v}
function headerMap(table){const rows=[...table.rows];for(const r of rows.slice(0,7)){const c=[...r.cells].map(x=>norm(x.innerText));const m={};c.forEach((x,i)=>{if(/細項名稱|檢驗名稱/.test(x))m.name=i;if(/檢驗值/.test(x))m.value=i;if(/完報日期|最終完報日時/.test(x))m.date=i;if(/^單位$/.test(x))m.unit=i;if(/^正常$|參考值|正常值/.test(x))m.normal=i;});if(m.name!==undefined&&m.value!==undefined)return m;}return null}
function sectionText(table){let t=norm(table.innerText);const prev=table.previousElementSibling;if(prev)t+=' '+norm(prev.innerText);return t.slice(0,1600)}
function refBounds(s){s=norm(s).replace(/[～~]/g,'-');let m=s.match(/(-?\d+(?:\.\d+)?)\s*-\s*(-?\d+(?:\.\d+)?)/);if(m)return{lo:+m[1],hi:+m[2]};m=s.match(/(?:<=|≤|<)\s*(-?\d+(?:\.\d+)?)/);if(m)return{lo:null,hi:+m[1]};m=s.match(/(?:>=|≥|>)\s*(-?\d+(?:\.\d+)?)/);if(m)return{lo:+m[1],hi:null};return{lo:null,hi:null}}
function calcFlag(value,normal,key){const x=Number(value);if(!Number.isFinite(x))return'';let {lo,hi}=refBounds(normal||'');if(key==='arr'&&hi==null)hi=20;if(key==='pac'&&hi==null)hi=15;if(lo!=null&&x<lo)return'L';if(hi!=null&&x>hi)return'H';return''}
function sourceFingerprint(){const parts=[location.href];for(const t of document.querySelectorAll('table')){if(t.closest('#'+ID))continue;parts.push(norm(t.innerText).slice(0,900))}let h=2166136261,s=parts.join('|');for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return String(h>>>0)}
function extractTables(){let added=0;state.age=state.age||ageOf(document.body.innerText);for(const table of document.querySelectorAll('table')){if(table.closest('#'+ID))continue;const map=headerMap(table);if(!map)continue;const sec=sectionText(table);const gasType=/venous blood gas/i.test(sec)?'VBG':(/blood gas|氣體分析/i.test(sec)?'ABG':'');for(const r of table.rows){const c=[...r.cells].map(x=>norm(x.innerText));if(c.length<=Math.max(map.name,map.value))continue;const name=c[map.name]||'';const key=classify(name,sec);if(!key)continue;const value=cleanResult(c[map.value],key);if(value==null)continue;const rowText=norm(r.innerText);const date=shortDate((map.date!==undefined?c[map.date]:'')||rowText),time=timeOf((map.date!==undefined?c[map.date]:'')||rowText),unit=(map.unit!==undefined?c[map.unit]:'')||unitMap[key]||'',normal=map.normal!==undefined?c[map.normal]:'';const flag=calcFlag(value,normal,key),sig=[key,date,time,value,gasType].join('|');if(!state.records[sig]){state.records[sig]={key,value,date,time,unit:unit.replace('10^3/ul','×10^3/uL'),name,gasType,normal,flag};added++;}}}save();return added}
function records(){return Object.values(state.records).sort((a,b)=>((b.date||'')+' '+(b.time||'')).localeCompare((a.date||'')+' '+(a.time||'')))}
function byDate(date){return records().filter(x=>x.date===date)}
function first(arr,key){return arr.find(x=>x.key===key)}
function shown(r){return r?`${r.flag||''}${r.value}`:null}
function value(arr,key){return shown(first(arr,key))}
function rawValue(arr,key){const r=first(arr,key);return r&&r.value}
function packPairs(arr,pairs,unit=''){const got=pairs.map(([k,l])=>[first(arr,k),l]).filter(([r])=>r);return got.length?`${got.map(x=>x[1]).join('/')} ${got.map(x=>shown(x[0])).join('/')}${unit?' '+unit:''}`:''}
function fib4(arr){const ast=+rawValue(arr,'ast'),alt=+rawValue(arr,'alt'),plt=+rawValue(arr,'plt'),age=state.age;if(!age||!ast||!alt||!plt)return'';const f=age*ast/(plt*Math.sqrt(alt));if(!isFinite(f))return'';const risk=age>=65?(f<2?'low':f<=2.67?'intermediate':'high'):(f<1.3?'low':f<=2.67?'intermediate':'high');return`FIB-4 ${f.toFixed(2)} (${risk} risk${age<35?'; limited accuracy age <35':''})`}
function fmtOPD(){const a=records(),lines=[];let p=[];const h=first(a,'hba1c'),e=first(a,'eag');if(h)p.push(`HbA1c ${shown(h)}%${e?` (eAG ${shown(e)} mg/dL)`:''}`);for(const [k,l,u] of [['gluac','Glu-AC','mg/dL'],['glupc2h','Glu-PC 2h','mg/dL'],['glupc','Glu-PC','mg/dL'],['uacr','UACR','mg/g'],['upcr','UPCR','mg/g']]){const r=first(a,k);if(r)p.push(`${l} ${shown(r)} ${u}`)}if(p.length)lines.push('• '+p.join('; '));p=[];const lip=packPairs(a,[['tc','TC'],['tg','TG'],['hdl','HDL'],['ldl','LDL']],'mg/dL');if(lip)p.push(lip);if(first(a,'ua'))p.push(`UA ${value(a,'ua')} mg/dL`);if(p.length)lines.push('• '+p.join('; '));p=[];const renal=packPairs(a,[['bun','BUN'],['cr','Cr'],['egfr','eGFR']]);if(renal)p.push(renal);const liver=packPairs(a,[['ast','AST'],['alt','ALT']],'U/L');if(liver)p.push(liver);if(p.length)lines.push('• '+p.join('; '));p=[];for(const [k,l,u] of [['tsh','TSH','uIU/mL'],['ft4','FT4','ng/dL'],['t3','T3','ng/mL']]){const r=first(a,k);if(r)p.push(`${l} ${shown(r)} ${u}`)}if(p.length)lines.push('• '+p.join('; '));p=[];for(const [k,l,u] of [['pac','PAC','ng/dL'],['pra','PRA','ng/mL/hr'],['arr','ARR','ng/dL/(ng/mL/hr)']]){const r=first(a,k);if(r)p.push(`${l} ${shown(r)} ${u}`)}if(p.length)lines.push('• '+p.join('; '));p=[];const c=packPairs(a,[['wbc','WBC'],['hb','Hb'],['plt','Plt']]);if(c)p.push(c);const f=fib4(a);if(f)p.push(f);if(p.length)lines.push('• '+p.join('; '));for(const r of Object.values(state.pathology).filter(x=>x.result))lines.push(`• ${r.label}: ${r.result}`);return lines.join('\n')}
function fmtUA(a){const p=[];for(const [k,l] of [['urineSG','SG'],['urinePH','pH'],['urinePro','Protein'],['urineGlu','Glucose'],['urineKet','Ketone'],['urineRBC','RBC'],['urineWBC','WBC'],['bacteria','Bacteria'],['urineNit','Nitrite'],['urineLE','LE']]){const r=first(a,k);if(r)p.push(`${l} ${shown(r)}${k==='urineRBC'||k==='urineWBC'?'/HPF':''}`)}return p.length?'U/A: '+p.join('; '):''}
function fmtDate(date){const a=byDate(date),lines=[date];let p=[];const cbc=packPairs(a,[['wbc','WBC'],['hb','Hb'],['plt','Plt']]);if(cbc)p.push('CBC: '+cbc);const diff=packPairs(a,[['neut','N'],['lymp','L'],['mono','M'],['eosi','E'],['baso','B']],'%');if(diff)p.push(diff);if(p.length)lines.push('• '+p.join('; '));p=[];const renal=packPairs(a,[['bun','BUN'],['cr','Cr'],['egfr','eGFR']]);if(renal)p.push(renal);const el=packPairs(a,[['na','Na'],['k','K'],['cl','Cl']]);if(el)p.push(el);const camg=packPairs(a,[['ca','Ca'],['p','P'],['mg','Mg']]);if(camg)p.push(camg);if(p.length)lines.push('• '+p.join('; '));p=[];const liver=packPairs(a,[['ast','AST'],['alt','ALT'],['tbil','T-bil'],['dbil','D-bil'],['alb','Alb']]);if(liver)p.push(liver);for(const [k,l,u] of [['crp','CRP','mg/dL'],['pct','PCT','ng/mL'],['lactate','Lactate','mg/dL'],['tnt','hs-TnT','ng/L']]){const r=first(a,k);if(r)p.push(`${l} ${shown(r)} ${u}`)}if(p.length)lines.push('• '+p.join('; '));const h=first(a,'hba1c'),e=first(a,'eag');if(h)lines.push(`• HbA1c ${shown(h)}%${e?` (eAG ${shown(e)} mg/dL)`:''}`);p=[];for(const [k,l,u] of [['gluac','Glu-AC','mg/dL'],['glupc2h','Glu-PC 2h','mg/dL'],['glupc','Glu-PC','mg/dL']]){const r=first(a,k);if(r)p.push(`${l} ${shown(r)} ${u}`)}if(p.length)lines.push('• '+p.join('; '));const coag=packPairs(a,[['pt','PT'],['inr','INR'],['aptt','aPTT']]);if(coag)lines.push('• '+coag);const ua=fmtUA(a);if(ua)lines.push('• '+ua);const bk=first(a,'bloodket');if(bk)lines.push(`• Blood ketone ${shown(bk)}`);for(const gt of ['ABG','VBG']){const g=a.filter(x=>x.gasType===gt);if(g.length){const gp=packPairs(g,[['ph','pH'],['pco2','pCO2'],['hco3','HCO3'],['be','BE'],['po2','pO2'],['so2','sO2']]);if(gp)lines.push(`• ${gt}: ${gp}`)}}const glucose=a.filter(x=>x.key==='glucose').sort((x,y)=>(x.time||'').localeCompare(y.time||''));if(glucose.length)lines.push('• Glucose: '+glucose.map(x=>`${x.time||'--:--'} ${shown(x)}`).join(' → ')+' mg/dL');p=[];for(const [k,l,u] of [['pac','PAC','ng/dL'],['pra','PRA','ng/mL/hr'],['arr','ARR','ng/dL/(ng/mL/hr)']]){const r=first(a,k);if(r)p.push(`${l} ${shown(r)} ${u}`)}if(p.length)lines.push('• '+p.join('; '));for(const [k,l] of [['stoolob','Stool OB'],['stooltf','Stool transferrin']]){const r=first(a,k);if(r)lines.push(`• ${l} ${shown(r)}`)}for(const c of Object.values(state.cultures).filter(x=>x.date===date&&x.result))lines.push(`• ${c.label}: ${c.result}`);for(const r of Object.values(state.pathology).filter(x=>x.date===date&&x.result))lines.push(`• ${r.label}: ${r.result}`);return lines.join('\n')}
function output(){const mode=detectMode();if(mode==='OPD')return fmtOPD();const ds=[...new Set(records().map(x=>x.date).filter(Boolean))].sort().reverse();let out=ds.map(fmtDate).filter(Boolean).join('\n\n');const undated=[...Object.values(state.cultures),...Object.values(state.pathology)].filter(x=>!x.date&&x.result);if(undated.length)out+=(out?'\n\n':'')+undated.map(x=>`• ${x.label}: ${x.result}`).join('\n');return out}
let activeCulture=null,activePathology=null;
function cultureFromNode(node){const tr=node&&node.closest&&node.closest('tr');if(!tr)return null;const txt=norm(tr.innerText);if(!/culture|培養/i.test(txt))return null;const table=tr.closest('table');const sec=table?sectionText(table):txt;const specimen=/tip/i.test(txt+sec)?'Tip':/urine|尿/i.test(txt+sec)?'Urine':/blood|血液|血培/i.test(txt+sec)?'Blood':'';const label=/tip/i.test(txt)?'Tip culture':/urine/i.test(txt)?'Urine culture':/anaer|厭氧/i.test(txt)?'Blood culture (anaerobic)':'Blood culture';const date=shortDate(txt+sec),time=timeOf(txt),key=[label,specimen,date,time,txt.slice(0,100)].join('|');return{key,label,specimen,date,time,rowText:txt}}
function pathologyFromNode(node){const tr=node&&node.closest&&node.closest('tr');if(!tr)return null;const txt=norm(tr.innerText);if(!/surgical\s*pathology|病理(?:組織|切片|檢查)|病理報告/i.test(txt))return null;const table=tr.closest('table'),sec=table?sectionText(table):txt,date=shortDate(txt+sec),time=timeOf(txt),label='Surgical pathology',key=[label,date,time,txt.slice(0,120)].join('|');return{key,label,date,time,rowText:txt}}
function setActive(node){const c=cultureFromNode(node);if(c){activeCulture=c;activePathology=null;focusEl.textContent=`Focus: ${c.label}${c.date?' '+c.date:''}`;return}const p=pathologyFromNode(node);if(p){activePathology=p;activeCulture=null;focusEl.textContent=`Focus: ${p.label}${p.date?' '+p.date:''}`}}
function visible(el){const r=el.getBoundingClientRect(),cs=getComputedStyle(el);return r.width>0&&r.height>0&&cs.display!=='none'&&cs.visibility!=='hidden'&&+cs.opacity!==0}
function visiblePanels(){return [...document.querySelectorAll('div,table,tbody,tr,td')].filter(el=>!el.closest('#'+ID)&&visible(el)).map(el=>norm(el.innerText)).filter(t=>t&&t.length<5000)}
function parseVisibleCultureResult(){if(!activeCulture)return;let best=null;for(const t of visiblePanels()){if(!/結果值\s*[:：]/.test(t)||t.length>1200)continue;if(!best||t.length<best.length)best=t}if(!best)return;const rm=best.match(/結果值\s*[:：]\s*([^\n]+)/i),sm=best.match(/檢體\s*[:：]\s*([^\n]+)/i);if(!rm)return;const result=norm(rm[1]),spec=sm?norm(sm[1]):'';if(spec&&activeCulture.specimen&&!new RegExp(activeCulture.specimen,'i').test(spec))return;if(!result||/^\d{1,3}$/.test(result))return;state.cultures[activeCulture.key]={...activeCulture,result};save()}
function parseVisiblePathologyResult(){if(!activePathology)return;let candidate='';for(const t of visiblePanels()){if(!/surgical\s*pathology|病理|diagnosis|診斷|結果值/i.test(t))continue;if(t.length<30||t.length>4500)continue;let m=t.match(/(?:病理診斷|診斷結果|Diagnosis|Final Diagnosis|結果值)\s*[:：]?\s*([\s\S]{10,2500})/i);if(m){candidate=norm(m[1]);break}}if(!candidate)return;candidate=candidate.replace(/備註\s*[:：][\s\S]*$/i,'').trim();if(candidate.length>1200)candidate=candidate.slice(0,1200)+'…';state.pathology[activePathology.key]={...activePathology,result:candidate};save()}
document.addEventListener('mousemove',e=>{for(const el of document.elementsFromPoint(e.clientX,e.clientY)){const c=cultureFromNode(el);if(c){activeCulture=c;activePathology=null;focusEl.textContent=`Focus: ${c.label}${c.date?' '+c.date:''}`;break}const p=pathologyFromNode(el);if(p){activePathology=p;activeCulture=null;focusEl.textContent=`Focus: ${p.label}${p.date?' '+p.date:''}`;break}}},{capture:true,passive:true});
document.addEventListener('click',e=>setActive(e.target),true);
const box=document.createElement('div');box.id=ID;Object.assign(box.style,{position:'fixed',right:'12px',top:'12px',zIndex:2147483647,width:'min(760px,calc(100vw - 24px))',maxHeight:'calc(100vh - 24px)',overflow:'auto',background:'#fff',color:'#243746',border:'1px solid #cfd4dc',borderRadius:'14px',boxShadow:'0 12px 40px rgba(0,0,0,.24)',padding:'14px',fontFamily:'Arial,"Microsoft JhengHei",sans-serif'});
box.innerHTML=`<div style="display:flex;justify-content:space-between;align-items:center;gap:8px"><strong>Auto Clinical Lab ${VERSION}</strong><button id="x" style="border:0;background:#fff;font-size:20px">×</button></div><div style="display:flex;gap:8px;align-items:center;flex-wrap:wrap;margin:8px 0"><label>Mode</label><select id="mode"><option>AUTO</option><option>OPD</option><option>ER</option><option>Inpatient</option></select><span id="det" style="font-size:12px;color:#667085"></span></div><div id="focus" style="font-size:12px;color:#9a3412;margin:4px 0">Focus: none</div><pre id="res" style="white-space:pre-wrap;line-height:1.65;background:#f8fafc;padding:10px;border-radius:9px;font:14px/1.65 inherit;min-height:44px"></pre><div style="display:flex;gap:8px;flex-wrap:wrap"><button id="copy" style="padding:8px 14px;border:0;border-radius:8px;background:#059669;color:#fff;font-weight:700">Copy</button><button id="clear" style="padding:8px 14px;border:1px solid #ccd5dd;border-radius:8px;background:#fff">Clear cache</button></div><div id="meta" style="font-size:12px;color:#667085;margin-top:7px"></div>`;document.body.appendChild(box);
const res=box.querySelector('#res'),meta=box.querySelector('#meta'),det=box.querySelector('#det'),focusEl=box.querySelector('#focus'),modeSel=box.querySelector('#mode');modeSel.value=state.modeOverride||'AUTO';
modeSel.onchange=()=>{state.modeOverride=modeSel.value;state.blockedFingerprint=null;save();refresh()};
let timer;function refresh(){const fp=sourceFingerprint();if(state.blockedFingerprint&&fp===state.blockedFingerprint){res.textContent='';det.textContent=`Detected: ${detectMode()}`;meta.textContent='Cache cleared ｜ 等待頁面資料變更';return}if(state.blockedFingerprint&&fp!==state.blockedFingerprint){state.blockedFingerprint=null;save()}extractTables();parseVisibleCultureResult();parseVisiblePathologyResult();res.textContent=output();det.textContent=`Detected: ${detectMode()}`;meta.textContent=`Age: ${state.age??'未讀取'} ｜ Labs ${records().length} ｜ Cultures ${Object.keys(state.cultures).length} ｜ Pathology ${Object.keys(state.pathology).length} ｜ ${new Date().toLocaleTimeString()}`}
function schedule(){clearTimeout(timer);timer=setTimeout(refresh,180)}const mo=new MutationObserver(muts=>{if(muts.every(m=>m.target&&m.target.closest&&m.target.closest('#'+ID)))return;schedule()});mo.observe(document.body,{subtree:true,childList:true,characterData:true});window.addEventListener('scroll',schedule,{passive:true});
box.querySelector('#copy').onclick=async()=>{try{await navigator.clipboard.writeText(res.textContent)}catch(e){const t=document.createElement('textarea');t.value=res.textContent;document.body.appendChild(t);t.select();document.execCommand('copy');t.remove()}};
box.querySelector('#clear').onclick=()=>{const fp=sourceFingerprint();state={records:{},cultures:{},pathology:{},age:ageOf(document.body.innerText),modeOverride:modeSel.value,blockedFingerprint:fp};save();activeCulture=null;activePathology=null;focusEl.textContent='Focus: none';res.textContent='';meta.textContent='Cache cleared ｜ 等待頁面資料變更'};
box.querySelector('#x').onclick=()=>{mo.disconnect();box.remove()};refresh();
})();
